export {resolve} from './resolve'
export {product} from './product'
export {concat} from './concat'
export {map} from './map'
export {indexed} from './indexed'
export {some} from './some'
export {every} from './every'
